# Generated by Django 5.0.2 on 2024-02-15 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='frame_path',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Animal'), ('2', 'Person'), ('3', 'Vehicle')], max_length=1)),
                ('confidence', models.FloatField()),
                ('x_coord', models.FloatField()),
                ('y_cood', models.FloatField()),
                ('box_width', models.FloatField()),
                ('box_height', models.FloatField()),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.frame')),
            ],
        ),
    ]
