# Generated by Django 5.0.2 on 2024-02-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_rename_y_cood_detection_y_coord'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='path',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
