# Generated by Django 5.0.2 on 2024-03-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0004_video_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='frame_path',
        ),
        migrations.AddField(
            model_name='frame',
            name='frame_data',
            field=models.BinaryField(null=True),
        ),
    ]
