# Generated by Django 5.0.2 on 2024-03-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0005_remove_frame_frame_path_frame_frame_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='status',
            field=models.CharField(choices=[('ENQUEUED', 'Enqueued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, max_length=10),
        ),
    ]
