# Generated by Django 5.0.2 on 2024-03-10 14:26

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0006_alter_frame_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='frame_data',
        ),
        migrations.RemoveField(
            model_name='video',
            name='path',
        ),
        migrations.AddField(
            model_name='frame',
            name='frame_file',
            field=models.FileField(null=True, storage=storages.backends.s3.S3Storage(bucket_name='evz-frames-bucket'), upload_to=''),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(null=True, storage=storages.backends.s3.S3Storage(bucket_name='evz-videos-bucket'), upload_to=''),
        ),
    ]
