# Generated by Django 5.0.2 on 2024-06-27 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0010_remove_frame_video_videochunk_frame_video_chunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='video_chunk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processor.video'),
        ),
        migrations.DeleteModel(
            name='VideoChunk',
        ),
    ]
