# Generated by Django 5.0.2 on 2024-06-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0014_videochunk_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='videochunk',
            name='sequence_number',
            field=models.IntegerField(default=1),
        ),
    ]
