# Generated by Django 5.0.2 on 2024-06-29 15:13

import django.core.files.storage
import processor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0016_video_frame_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='detections_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='frames', location='/home/eric/code/animal-celery/video_processor/frames'), upload_to=processor.models.detection_upload_path),
        ),
    ]
