# Generated by Django 5.0.2 on 2024-06-29 16:18

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0017_frame_detections_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='detections_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='videos', location='/home/eric/code/animal-celery/video_processor/videos'), upload_to=''),
        ),
    ]
