# Generated by Django 5.0.2 on 2025-08-17 15:03

import django.core.files.storage
import processor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0018_video_detections_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='detections_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='frames', location='/output/frames'), upload_to=processor.models.detection_upload_path),
        ),
        migrations.AlterField(
            model_name='frame',
            name='frame_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='frames', location='/output/frames'), upload_to=processor.models.frame_upload_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='detections_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='videos', location='/output/videos'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='videos', location='/output/videos'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='videochunk',
            name='video_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='videos', location='/output/videos'), upload_to=''),
        ),
    ]
