# Generated by Django 5.0.2 on 2026-01-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0019_alter_frame_detections_file_alter_frame_frame_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videochunk',
            name='end_frame',
            field=models.IntegerField(help_text='Last frame number in this chunk', null=True),
        ),
        migrations.AddField(
            model_name='videochunk',
            name='start_frame',
            field=models.IntegerField(help_text='First frame number in this chunk', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='frame_rate',
            field=models.FloatField(default=20.0),
        ),
    ]
