# Generated by Django 5.0.2 on 2026-01-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0020_videochunk_end_frame_videochunk_start_frame_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videochunk',
            name='frame_count',
            field=models.IntegerField(help_text='Number of frames in this chunk', null=True),
        ),
    ]
