# Generated by Django 5.0.2 on 2026-01-28 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0021_add_frame_count_to_videochunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.IntegerField()),
                ('category', models.CharField(choices=[('1', 'Animal'), ('2', 'Person'), ('3', 'Vehicle')], max_length=1)),
                ('start_frame', models.IntegerField()),
                ('end_frame', models.IntegerField()),
                ('total_displacement', models.FloatField(default=0.0)),
                ('is_static', models.BooleanField(default=False)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.video')),
            ],
            options={
                'unique_together': {('video', 'track_id')},
            },
        ),
        migrations.AddField(
            model_name='detection',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processor.track'),
        ),
    ]
