# Generated by Django 5.0.2 on 2026-01-29 13:17

import django.core.files.storage
import processor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0022_track_detection_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='frame',
            name='detections_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/frames/', location='/output/frames'), upload_to=processor.models.detection_upload_path),
        ),
        migrations.AlterField(
            model_name='frame',
            name='frame_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/frames/', location='/output/frames'), upload_to=processor.models.frame_upload_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='detections_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/videos/', location='/output/videos'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/videos/', location='/output/videos'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='videochunk',
            name='video_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/videos/', location='/output/videos'), upload_to=''),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='videos', to='processor.tag'),
        ),
    ]
