# Generated by Django 5.0.2 on 2026-01-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0023_add_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='status',
            field=models.CharField(choices=[('ENQUEUED', 'Enqueued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('DELETED', 'Deleted')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('ENQUEUED', 'Enqueued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('DELETED', 'Deleted')], default='ENQUEUED', max_length=10),
        ),
        migrations.AlterField(
            model_name='videochunk',
            name='status',
            field=models.CharField(choices=[('ENQUEUED', 'Enqueued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('DELETED', 'Deleted')], default='ENQUEUED', max_length=10),
        ),
    ]
