version: '3'
services:
  
  analyze:
    image: animals:latest
    depends_on:
      - db
    volumes:
      - .:/code
      - /mnt/d379e10e-9348-43b8-b3b0-e6ea12f8e892:/output
      - ./input:/input
    environment:
      EXTRACT_WORKER_COUNT: 1
      FRAMES_OUTPUT_PATH: '/output'
      DJANGO_SECRET_KEY: foobar
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: processor
      DB_USER: processor
      DB_PASSWORD: processor-password
      DJANGO_SUPERUSER_USERNAME: evz
      DJANGO_SUPERUSER_PASSWORD: letmeinnow
      DJANGO_SUPERUSER_EMAIL: test@test.com
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    command: ['celery', '-A', 'video_processor', 'worker', '-l', 'INFO', '-Q', 'analyze', '--concurrency', '1']
  
  extract:
    image: animals:latest
    depends_on:
      - db
    volumes:
      - .:/code
      - /mnt/d379e10e-9348-43b8-b3b0-e6ea12f8e892:/output
      - ./input:/input
    environment:
      EXTRACT_WORKER_COUNT: 1
      FRAMES_OUTPUT_PATH: '/output'
      DJANGO_SECRET_KEY: foobar
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: processor
      DB_USER: processor
      DB_PASSWORD: processor-password
      DJANGO_SUPERUSER_USERNAME: evz
      DJANGO_SUPERUSER_PASSWORD: letmeinnow
      DJANGO_SUPERUSER_EMAIL: test@test.com
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    command: ['celery', '-A', 'video_processor', 'worker', '-l', 'INFO', '-Q', 'extract', '--concurrency', '1']
    deploy:
      replicas: 1
  
  detector:
    image: megadetector:latest
    expose:
      - '1213'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  detect:
    image: animals:latest
    depends_on:
      - db
      - detector
    volumes:
      - .:/code
      - /mnt/d379e10e-9348-43b8-b3b0-e6ea12f8e892:/output
      - ./input:/input
      - ./models:/models
    environment:
      EXTRACT_WORKER_COUNT: 1
      DETECTOR_API_HOST: detector
      FRAMES_OUTPUT_PATH: '/output'
      DJANGO_SECRET_KEY: foobar
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: processor
      DB_USER: processor
      DB_PASSWORD: processor-password
      DJANGO_SUPERUSER_USERNAME: evz
      DJANGO_SUPERUSER_PASSWORD: letmeinnow
      DJANGO_SUPERUSER_EMAIL: test@test.com
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    command: ['celery', '-A', 'video_processor', 'worker', '-l', 'INFO', '-Q', 'detect', '--concurrency', '1']
    deploy:
      replicas: 1
  
  db:
    image: 'postgres:15'
    environment:
      POSTGRES_PASSWORD: processor-password
      POSTGRES_USER: processor
      POSTGRES_DB: processor
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - detector
    ports:
      - "4000:4000"
    expose:
    - '4000'

volumes:
  postgresql:
  postgresql_data:
