version: '3'
services:
  
  analyze:
    image: animals:latest
    volumes:
      - .:/code
      - /mnt/d379e10e-9348-43b8-b3b0-e6ea12f8e892:/output
      - ./input:/input
    environment:
      EXTRACT_WORKER_COUNT: 4
      FRAMES_OUTPUT_PATH: '/output'
      DJANGO_SECRET_KEY: foobar
      DB_HOST: ec2-3-145-168-225.us-east-2.compute.amazonaws.com
      DB_PORT: 5432
      DB_NAME: processor
      DB_USER: processor
      DB_PASSWORD: 'HTX5>}{8Qzv27k0if|EW{ZW0lLBD'
      DJANGO_SUPERUSER_USERNAME: evz
      DJANGO_SUPERUSER_PASSWORD: letmeinnow
      DJANGO_SUPERUSER_EMAIL: test@test.com
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    command: ['celery', '-A', 'video_processor', 'worker', '-l', 'INFO', '-Q', 'analyze', '--concurrency', '1']
  
  extract:
    image: animals:latest
    volumes:
      - .:/code
      - /mnt/d379e10e-9348-43b8-b3b0-e6ea12f8e892:/output
    environment:
      EXTRACT_WORKER_COUNT: 4
      FRAMES_OUTPUT_PATH: '/output'
      DJANGO_SECRET_KEY: foobar
      DB_HOST: ec2-3-145-168-225.us-east-2.compute.amazonaws.com
      DB_PORT: 5432
      DB_NAME: processor
      DB_USER: processor
      DB_PASSWORD: processor-password
      DJANGO_SUPERUSER_USERNAME: evz
      DJANGO_SUPERUSER_PASSWORD: letmeinnow
      DJANGO_SUPERUSER_EMAIL: test@test.com
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    command: ['celery', '-A', 'video_processor', 'worker', '-l', 'INFO', '-Q', 'extract', '--concurrency', '1']
    deploy:
      replicas: 2
  
  detect:
    image: animals:latest
    volumes:
      - .:/code
      - /mnt/d379e10e-9348-43b8-b3b0-e6ea12f8e892:/output
    environment:
      EXTRACT_WORKER_COUNT: 1
      DETECTOR_API_HOST: detector
      FRAMES_OUTPUT_PATH: '/output'
      DJANGO_SECRET_KEY: foobar
      DB_HOST: ec2-3-145-168-225.us-east-2.compute.amazonaws.com
      DB_PORT: 5432
      DB_NAME: processor
      DB_USER: processor
      DB_PASSWORD: processor-password
      DJANGO_SUPERUSER_USERNAME: evz
      DJANGO_SUPERUSER_PASSWORD: letmeinnow
      DJANGO_SUPERUSER_EMAIL: test@test.com
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      LOAD_MODEL: 'yes'
    command: ['celery', '-A', 'video_processor', 'worker', '-l', 'INFO', '-Q', 'detect', '--concurrency', '1']
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
